### ISSUE TITLE
使用nginx提供https反代时部分功能受影响

### ISSUE THREAD

**Issue by nebulakl** [ronggang/transmission-web-control#175]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 2.93 (3c5870d4f5), RPC: 15
* Tr Web Control 版本: 1.5.1 update-2 (20180330)
* 浏览器名称及版本：Chrome 64.0.3282.190
* 问题描述: 

1. 侧边栏图标变成黑白，文件夹不勾也会显示
![screenshot 2018-03-30 at 14 35 01](https://user-images.githubusercontent.com/12024936/38149216-b5827af8-3427-11e8-9c8d-6aeca83d8370.png)

2. Mobile UI 不工作
![screenshot 2018-03-30 at 14 38 28](https://user-images.githubusercontent.com/12024936/38149287-0b1ef036-3428-11e8-847b-7d74f83d4d9a.png)

Console output
```
index.mobile.html:24 GET https://....../trans/transmission/web/tr-web-control/script/min/cookies.min.js?v=20171015.1 net::ERR_ABORTED
index.mobile.html:24 GET https://....../trans/transmission/web/tr-web-control/script/min/cookies.min.js?v=20171015.1 net::ERR_ABORTED
jquery.mobile-1.4.5.min.js?v=20170426:3 Uncaught DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'https://....../trans/transmission/web/index.mobile.html' cannot be created in a document with origin 'https://......' and URL 'https://....../trans/transmission/web/index.mobile.html'.
    at a.mobile.Navigator.squash (https://....../trans/transmission/web/tr-web-control/script/jquery/mobile/jquery.mobile-1.4.5.min.js?v=20170426:3:31660)
    at Object.initializePage (https://....../trans/transmission/web/tr-web-control/script/jquery/mobile/jquery.mobile-1.4.5.min.js?v=20170426:9:6549)
    at HTMLDocument.<anonymous> (https://....../trans/transmission/web/tr-web-control/script/jquery/mobile/jquery.mobile-1.4.5.min.js?v=20170426:9:6881)
    at i (https://....../trans/transmission/web/tr-web-control/script/jquery/jquery-1.12.4.min.js:2:27449)
    at Object.fireWith [as resolveWith] (https://....../trans/transmission/web/tr-web-control/script/jquery/jquery-1.12.4.min.js:2:28213)
    at Function.ready (https://....../trans/transmission/web/tr-web-control/script/jquery/jquery-1.12.4.min.js:2:30006)
    at HTMLDocument.K (https://....../trans/transmission/web/tr-web-control/script/jquery/jquery-1.12.4.min.js:2:30368)
squash @ jquery.mobile-1.4.5.min.js?v=20170426:3
initializePage @ jquery.mobile-1.4.5.min.js?v=20170426:9
(anonymous) @ jquery.mobile-1.4.5.min.js?v=20170426:9
i @ jquery-1.12.4.min.js:2
fireWith @ jquery-1.12.4.min.js:2
ready @ jquery-1.12.4.min.js:2
K @ jquery-1.12.4.min.js:2
favicon.ico:1 GET https://....../favicon.ico 404 ()
```

3. 这个可能跟这个项目没啥关系，不过 Original UI 无限刷新，只能看不能动。

nginx/1.13.10 相关设置
```
location /trans/ {
	proxy_set_header	X-Forwarded-Host $host:$server_port;
	proxy_set_header	X-Forwarded-Server $host;
	proxy_set_header	X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_pass              http://127.0.0.1:9091/;
	}
```

**Comment by ronggang** [comment]
请尝试恢复默认设置
![47554516-5407-4900-a8c3-63cd93226788](https://user-images.githubusercontent.com/8065899/38158307-5a847b4a-34c4-11e8-8624-bd577317ef9a.jpeg)

**Comment by ronggang** [comment]
另外，1.5之后，图标逐步变为单色的，请知晓
mobile ui一直没有更新，如果之前正常的，现在应该也可以的；
原版ui需要官方的内容支持

**Comment by nebulakl** [comment]
Restore UI Default Settings 后 mobile ui 跟 original ui 都恢复了正常，然而每次清除浏览器数据后都要 restore 一次。这大概只能算作 workaround 吧。
